config/routes.rb
Rails.application.routes.draw do
  resources :location_data
  resources :economics
  resources :populations
  resources :postcodes
  resources :lower_layer_output_areas
  resources :middle_layer_output_areas
  resources :wards
  resources :district_postcodes
  resources :districts
  resources :countries do
    collection { post :import }
  end

# IKKE I BRUK LENGRE
#  get '/areas/districts/:district', :to => 'areas#district', as: 'areas_districts'
#  get '/areas/wards/:ward', :to => 'areas#ward', as: 'areas_wards'


  resources :addresses
  # FOLLOWS ROUTES
  resources :follow, only: [:create, :destroy]

  # STATIC PAGES
  root 'static_pages#index'

  # USERS ROUTES
  resources :users, only: [:show]
  get "search", :to => "users#search"

  # IMPORT ROUTES
  get "import", :to => "imports#index"
  post "import_countries", :to => "imports#area_import"
  post "import_postcodes", :to => "imports#import"

  # DEVISE RELATED
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :districts, -> { order(:district => :asc) }
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :country
  has_many :district_postcodes, -> { order(:district_postcode => :asc) }
  has_many :wards, -> { order(:ward => :asc) }
end

app/models/district_postcode.rb
class DistrictPostcode < ApplicationRecord
  belongs_to :district
  has_many :postcodes
end

app/models/economic.rb
class Economic < ApplicationRecord
  belongs_to :lower_layer_output_area
end

app/models/follow.rb
class Follow < ApplicationRecord
  # Search for users
  #include PgSearch
  #pg_search_scope :search_by_full_name, against: [:first_name, :last_name]

  # The user giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  # The user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/location_datum.rb
class LocationDatum < ApplicationRecord
  belongs_to :postcode
end

app/models/population.rb
class Population < ApplicationRecord
  belongs_to :ward
end

app/models/postcode.rb
class Postcode < ApplicationRecord
  belongs_to :lower_layer_output_area
  belongs_to :district_postcode
  has_many :location_datum

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# PG search for model
include PgSearch::Model
#pg_search_scope :search_by_full_name, against: [:first_name, :last_name],
#                  using: [:tsearch, :trigram]



# FOLLOW FEATURE
  # Returns array of follows for given user
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

  # Returns array of users who follow given user
  has_many :followers, through: :received_follows, source: :follower

  # returns array of follows a user has to other users
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"

  # returns array of other users who the user has followed.
  has_many :followings, through: :given_follows, source: :followed_user

end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :district
  has_many :middle_layer_output_areas
  has_many :populations
end

app/controllers/district_postcodes_controller.rb
class DistrictPostcodesController < ApplicationController
  before_action :set_district_postcode, only: [:show, :edit, :update, :destroy]

  # GET /district_postcodes
  # GET /district_postcodes.json
  def index
    @district_postcodes = DistrictPostcode.all
  end

  # GET /district_postcodes/1
  # GET /district_postcodes/1.json
  def show
  end

  # GET /district_postcodes/new
  def new
    @district_postcode = DistrictPostcode.new
  end

  # GET /district_postcodes/1/edit
  def edit
  end

  # POST /district_postcodes
  # POST /district_postcodes.json
  def create
    @district_postcode = DistrictPostcode.new(district_postcode_params)

    respond_to do |format|
      if @district_postcode.save
        format.html { redirect_to @district_postcode, notice: 'District postcode was successfully created.' }
        format.json { render :show, status: :created, location: @district_postcode }
      else
        format.html { render :new }
        format.json { render json: @district_postcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /district_postcodes/1
  # PATCH/PUT /district_postcodes/1.json
  def update
    respond_to do |format|
      if @district_postcode.update(district_postcode_params)
        format.html { redirect_to @district_postcode, notice: 'District postcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @district_postcode }
      else
        format.html { render :edit }
        format.json { render json: @district_postcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /district_postcodes/1
  # DELETE /district_postcodes/1.json
  def destroy
    @district_postcode.destroy
    respond_to do |format|
      format.html { redirect_to district_postcodes_url, notice: 'District postcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district_postcode
      @district_postcode = DistrictPostcode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def district_postcode_params
      params.require(:district_postcode).permit(:district_postcode, :district_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # SVG support, to use surrond in any tag with class of color wanted. Then: <%= svg 'name_of_svg' %>
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/svg/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end

  # FLASH message helper
  def flash_type_helper(type, msg)
    if type == "alert"
      flash_message = "<div class='alert alert-warning fade-away'>#{msg}</div>"
    elsif type == "notice"
      flash_message = "<div class='alert alert-success fade-away'>#{msg}</div>"
    elsif type == "error"
      flash_message = "<div class='alert alert-danger fade-away'>#{msg}</div>"
    end
    flash_message.html_safe
  end

  # First name helper to find out if the name is to long
  def first_name_welcome_helper
    if !current_user || current_user.first_name == nil || current_user.first_name.size > 6
      "Welcome"
    else
      "Welcome #{current_user.first_name.capitalize}"
    end
  end
end

app/helpers/countries_helper.rb
module CountriesHelper


end

app/helpers/district_postcodes_helper.rb
module DistrictPostcodesHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper



end

app/helpers/economics_helper.rb
module EconomicsHelper
end

app/helpers/follow_helper.rb
module FollowHelper

  def current_user_following (y)
    x = current_user.id
    f = Follow.where(follower_id: x, followed_user_id: y).or(Follow.where(follower_id: y, followed_user_id: x))
    if f.empty?
      false
    else
      true
    end
  end

end

app/helpers/populations_helper.rb
module PopulationsHelper
end

app/helpers/postcodes_helper.rb
module PostcodesHelper
end

app/helpers/wards_helper.rb
module WardsHelper


end

app/views/district_postcodes/_form.html.erb
<%= form_with(model: district_postcode, local: true) do |form| %>
  <% if district_postcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(district_postcode.errors.count, "error") %> prohibited this district_postcode from being saved:</h2>

      <ul>
        <% district_postcode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :district_postcode %>
    <%= form.text_field :district_postcode %>
  </div>

  <div class="field">
    <%= form.label :district_id %>
    <%= form.text_field :district_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/district_postcodes/edit.html.erb
<h1>Editing District Postcode</h1>

<%= render 'form', district_postcode: @district_postcode %>

<%= link_to 'Show', @district_postcode %> |
<%= link_to 'Back', district_postcodes_path %>

app/views/district_postcodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>District Postcodes</h1>

<table>
  <thead>
    <tr>
      <th>District postcode</th>
      <th>District</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @district_postcodes.each do |district_postcode| %>
      <tr>
        <td><%= district_postcode.district_postcode %></td>
        <td><%= district_postcode.district_id %></td>
        <td><%= link_to 'Show', district_postcode %></td>
        <td><%= link_to 'Edit', edit_district_postcode_path(district_postcode) %></td>
        <td><%= link_to 'Destroy', district_postcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District Postcode', new_district_postcode_path %>

app/views/district_postcodes/new.html.erb
<h1>New District Postcode</h1>

<%= render 'form', district_postcode: @district_postcode %>

<%= link_to 'Back', district_postcodes_path %>

app/views/district_postcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>District postcode:</strong>
  <%= @district_postcode.district_postcode %>
</p>

<p>
  <strong>District:</strong>
  <%= @district_postcode.district_id %>
</p>

<%= link_to 'Edit', edit_district_postcode_path(@district_postcode) %> |
<%= link_to 'Back', district_postcodes_path %>