config/routes.rb
Rails.application.routes.draw do
  resources :location_data
  resources :economics
  resources :populations
  resources :postcodes
  resources :lower_layer_output_areas
  resources :middle_layer_output_areas
  resources :wards
  resources :district_postcodes
  resources :districts
  resources :countries do
    collection { post :import }
  end

# IKKE I BRUK LENGRE
#  get '/areas/districts/:district', :to => 'areas#district', as: 'areas_districts'
#  get '/areas/wards/:ward', :to => 'areas#ward', as: 'areas_wards'


  resources :addresses
  # FOLLOWS ROUTES
  resources :follow, only: [:create, :destroy]

  # STATIC PAGES
  root 'static_pages#index'

  # USERS ROUTES
  resources :users, only: [:show]
  get "search", :to => "users#search"

  # IMPORT ROUTES
  get "import", :to => "imports#index"
  post "import_countries", :to => "imports#area_import"
  post "import_postcodes", :to => "imports#import"

  # DEVISE RELATED
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :districts, -> { order(:district => :asc) }
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :country
  has_many :district_postcodes, -> { order(:district_postcode => :asc) }
  has_many :wards, -> { order(:ward => :asc) }
end

app/models/district_postcode.rb
class DistrictPostcode < ApplicationRecord
  belongs_to :district
  has_many :postcodes
end

app/models/economic.rb
class Economic < ApplicationRecord
  belongs_to :lower_layer_output_area
end

app/models/follow.rb
class Follow < ApplicationRecord
  # Search for users
  #include PgSearch
  #pg_search_scope :search_by_full_name, against: [:first_name, :last_name]

  # The user giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  # The user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/location_datum.rb
class LocationDatum < ApplicationRecord
  belongs_to :postcode
end

app/models/population.rb
class Population < ApplicationRecord
  belongs_to :ward
end

app/models/postcode.rb
class Postcode < ApplicationRecord
  belongs_to :lower_layer_output_area
  belongs_to :district_postcode
  has_many :location_datum

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# PG search for model
include PgSearch::Model
#pg_search_scope :search_by_full_name, against: [:first_name, :last_name],
#                  using: [:tsearch, :trigram]



# FOLLOW FEATURE
  # Returns array of follows for given user
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

  # Returns array of users who follow given user
  has_many :followers, through: :received_follows, source: :follower

  # returns array of follows a user has to other users
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"

  # returns array of other users who the user has followed.
  has_many :followings, through: :given_follows, source: :followed_user

end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :district
  has_many :middle_layer_output_areas
  has_many :populations
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: [:show, :edit, :update, :destroy]

  # GET /wards
  # GET /wards.json
  def index
    @wards = Ward.all
  end

  # GET /wards/1
  # GET /wards/1.json
  def show
    @ward = Ward.find_by_id(params[:id])
    @mloas = MiddleLayerOutputArea.where(ward_id: params[:id])
  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to @ward, notice: 'Ward was successfully created.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to @ward, notice: 'Ward was successfully updated.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to wards_url, notice: 'Ward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ward_params
      params.require(:ward).permit(:ward, :ward_code, :district_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # SVG support, to use surrond in any tag with class of color wanted. Then: <%= svg 'name_of_svg' %>
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/svg/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end

  # FLASH message helper
  def flash_type_helper(type, msg)
    if type == "alert"
      flash_message = "<div class='alert alert-warning fade-away'>#{msg}</div>"
    elsif type == "notice"
      flash_message = "<div class='alert alert-success fade-away'>#{msg}</div>"
    elsif type == "error"
      flash_message = "<div class='alert alert-danger fade-away'>#{msg}</div>"
    end
    flash_message.html_safe
  end

  # First name helper to find out if the name is to long
  def first_name_welcome_helper
    if !current_user || current_user.first_name == nil || current_user.first_name.size > 6
      "Welcome"
    else
      "Welcome #{current_user.first_name.capitalize}"
    end
  end
end

app/helpers/countries_helper.rb
module CountriesHelper


end

app/helpers/districts_helper.rb
module DistrictsHelper



end

app/helpers/economics_helper.rb
module EconomicsHelper
end

app/helpers/follow_helper.rb
module FollowHelper

  def current_user_following (y)
    x = current_user.id
    f = Follow.where(follower_id: x, followed_user_id: y).or(Follow.where(follower_id: y, followed_user_id: x))
    if f.empty?
      false
    else
      true
    end
  end

end

app/helpers/populations_helper.rb
module PopulationsHelper
end

app/helpers/postcodes_helper.rb
module PostcodesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/wards_helper.rb
module WardsHelper


end

app/views/wards/_form.html.erb
<%= form_with(model: ward, local: true) do |form| %>
  <% if ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
        <% ward.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ward %>
    <%= form.text_field :ward %>
  </div>

  <div class="field">
    <%= form.label :ward_code %>
    <%= form.text_field :ward_code %>
  </div>

  <div class="field">
    <%= form.label :district_id %>
    <%= form.text_field :district_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<h1>Editing Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Show', @ward %> |
<%= link_to 'Back', wards_path %>

app/views/wards/index.html.erb
<%= link_to 'Back', :back, class: "btn btn-outline-dark full-width mb-4" %>

<h1>Wards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Ward</th>
      <th>Ward code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wards.each do |ward| %>
      <tr>
        <td><%= ward.ward %></td>
        <td><%= ward.ward_code %></td>
        <td><%= link_to 'Show', ward, class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/wards/new.html.erb
<h1>New Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Back', wards_path %>

app/views/wards/show.html.erb
<%= link_to 'Back', :back, class: "btn btn-outline-dark full-width mb-4" %>

<div class="jumbotron">
  <h1><%= @ward.ward %></h1>
  <div class="row no-bullet-points">
    <div class="col-6">
      <ul>
        <li>Crime: 15%</li>
        <li>Population: 15 000</li>
        <li>Unemployment: 4.3%</li><br>
        <li>Average IMD: 4367</li>
        <li>Mean IMD: 5500</li><br>
        <li>Average salary: 25 000</li>
        <li>Mean salary: 23 000</li><br>
        <li>Average age: 45</li>
        <li>Mean age: 35</li>
      </ul>
    </div>
    <div class="col-6">
      <ul>
        <li>Train stations 230</li>
        <li>Hospitals 60</li>
        <li>Universites 63</li><br>
        <li>Average Houseprice: 120 000</li>
        <li>Average Rental (HMO): 95</li>
      </ul>
    </div>
  </div>
</div>

<h2>Middle Layer Output Areas in <%= @ward.ward %></h2>
  <p>There are <%= @mloas.count %> Middle Layer Output Areas (MLOA) in <%= @ward.ward %>.</p>
<% @mloas.each do |mloa| %>
<div class="accordion" id="accordionMloa">
  <div class="card">
    <div class="card-header" id="headingMloa-<%= mloa.id %>">
      <h2 class="mb-0">
        <div class="btn-group full-width">
          <div class="row full-width">
            <button class="btn btn-outline-info col-8 text-left" type="button" data-toggle="collapse" data-target="#collapse<%= mloa.id %>" aria-expanded="true" aria-controls="collapse<%= mloa.id %>">
              <span class="badge badge-info float-left mt-1"><%= mloa.msoa_code %></span><span class="ml-2"><%= mloa.middle_layer_output_area %></span>
            </button>


            <%= link_to "Explore", mloa, class: "btn btn-main col-4" %>
          </div>
        </div>
      </h2>
    </div>

    <div id="collapse<%= mloa.id %>" class="collapse" aria-labelledby="headingMloa-<%= mloa.id %>" data-parent="#accordionMloa">
      <div class="card-body">
        <p><%= mloa.middle_layer_output_area %> has <%= mloa.lower_layer_output_areas.count %> Lower Layer Output Areas. Population in <%= mloa.middle_layer_output_area %> is: POPULATION. Average rental price for a HMO bedroom is: 88 and average houseprice is: 95 000.</p>
        <div class="card-subtitle border-bottom-dark mt-2">
          Lower Layer Output Areas
        </div>
        <div class="">
          <% mloa.lower_layer_output_areas.each do |lloa| %>
              <%= link_to lloa.lower_layer_output_area, lower_layer_output_area_path(lloa.id), class: "badge badge-info" %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>
<% end %>