config/routes.rb
Rails.application.routes.draw do
  resources :location_data
  resources :economics
  resources :populations
  resources :postcodes
  resources :lower_layer_output_areas
  resources :middle_layer_output_areas
  resources :wards
  resources :district_postcodes
  resources :districts
  resources :countries do
    collection { post :import }
  end

# IKKE I BRUK LENGRE
#  get '/areas/districts/:district', :to => 'areas#district', as: 'areas_districts'
#  get '/areas/wards/:ward', :to => 'areas#ward', as: 'areas_wards'


  resources :addresses
  # FOLLOWS ROUTES
  resources :follow, only: [:create, :destroy]

  # STATIC PAGES
  root 'static_pages#index'

  # USERS ROUTES
  resources :users, only: [:show]
  get "search", :to => "users#search"

  # IMPORT ROUTES
  get "import", :to => "imports#index"
  post "import_countries", :to => "imports#area_import"
  post "import_postcodes", :to => "imports#import"

  # DEVISE RELATED
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :districts, -> { order(:district => :asc) }
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :country
  has_many :district_postcodes, -> { order(:district_postcode => :asc) }
  has_many :wards, -> { order(:ward => :asc) }
end

app/models/district_postcode.rb
class DistrictPostcode < ApplicationRecord
  belongs_to :district
  has_many :postcodes
end

app/models/economic.rb
class Economic < ApplicationRecord
  belongs_to :lower_layer_output_area
end

app/models/follow.rb
class Follow < ApplicationRecord
  # Search for users
  #include PgSearch
  #pg_search_scope :search_by_full_name, against: [:first_name, :last_name]

  # The user giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  # The user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/location_datum.rb
class LocationDatum < ApplicationRecord
  belongs_to :postcode
end

app/models/population.rb
class Population < ApplicationRecord
  belongs_to :ward
end

app/models/postcode.rb
class Postcode < ApplicationRecord
  belongs_to :lower_layer_output_area
  belongs_to :district_postcode
  has_many :location_datum

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# PG search for model
include PgSearch::Model
#pg_search_scope :search_by_full_name, against: [:first_name, :last_name],
#                  using: [:tsearch, :trigram]



# FOLLOW FEATURE
  # Returns array of follows for given user
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

  # Returns array of users who follow given user
  has_many :followers, through: :received_follows, source: :follower

  # returns array of follows a user has to other users
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"

  # returns array of other users who the user has followed.
  has_many :followings, through: :given_follows, source: :followed_user

end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :district
  has_many :middle_layer_output_areas
  has_many :populations
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # SVG support, to use surrond in any tag with class of color wanted. Then: <%= svg 'name_of_svg' %>
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/svg/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end

  # FLASH message helper
  def flash_type_helper(type, msg)
    if type == "alert"
      flash_message = "<div class='alert alert-warning fade-away'>#{msg}</div>"
    elsif type == "notice"
      flash_message = "<div class='alert alert-success fade-away'>#{msg}</div>"
    elsif type == "error"
      flash_message = "<div class='alert alert-danger fade-away'>#{msg}</div>"
    end
    flash_message.html_safe
  end

  # First name helper to find out if the name is to long
  def first_name_welcome_helper
    if !current_user || current_user.first_name == nil || current_user.first_name.size > 6
      "Welcome"
    else
      "Welcome #{current_user.first_name.capitalize}"
    end
  end
end

app/helpers/countries_helper.rb
module CountriesHelper


end

app/helpers/districts_helper.rb
module DistrictsHelper



end

app/helpers/economics_helper.rb
module EconomicsHelper
end

app/helpers/follow_helper.rb
module FollowHelper

  def current_user_following (y)
    x = current_user.id
    f = Follow.where(follower_id: x, followed_user_id: y).or(Follow.where(follower_id: y, followed_user_id: x))
    if f.empty?
      false
    else
      true
    end
  end

end

app/helpers/postcodes_helper.rb
module PostcodesHelper
end

app/helpers/wards_helper.rb
module WardsHelper


end

app/views/layouts/partials/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white pt-5 pb-5">
    <% if !user_signed_in? %>
      <%= link_to "Aviny", root_path, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_menu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon text-dark"></span>
    </button>

    <div class="collapse navbar-collapse" id="main_menu">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Following", user_path(current_user.id), class: "nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Areas", countries_path, class: "nav-link text-dark" %>
          </li>
          <% if current_user.admin? %>
            <%= link_to "Import", new_country_path, class: "nav-link text-dark" %>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up",  new_user_registration_path, class: "nav-link text-dark"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link text-dark"%>
          </li>
        <% end %>
      </ul>
<!--
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
      </form>
-->
    </div>
  </nav>

app/views/layouts/partials/_sidebar.html.erb
  <!-- Sidebar -->
  <nav class="navbar-vertical" role="navigation">
    <ul class="nav flex-column">
      <div class="navbar-brand">
          <%= link_to "#{first_name_welcome_helper}", root_path %>
      </div>
      <div class="navbar-elements navbar-elements-general">
        <% if user_signed_in? %>
          <li class="nav-item"><a class="nav-link navbar-each-element" href="#">Messages<span><i>+10</i><%= svg('messages') %></span></a></li>
          <li class="nav-item"><a class="nav-link navbar-each-element" href="#">Notifications<span><i>5</i><%= svg('notifications') %></span></a></li>
          <li class="nav-item"><a class="nav-link navbar-each-element" href="#">Your properties<span><i>0</i><%= svg('home') %></span></a></li>
          <li class="nav-item">
            <%= link_to countries_path, class: "nav-link navbar-each-element" do %>
              Research <span><%= svg('statistics') %></span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user.id), class: "nav-link navbar-each-element" do %>
              Collaborate <span><%= svg('collaboration') %></span>
            <% end %>
         </li>
          <li class="nav-item"><a class="nav-link navbar-each-element" href="#">Financing<span><%= svg('money') %></span></a></li>
          <li class="nav-item"><a class="nav-link navbar-each-element" href="#">Services<span><%= svg('services') %></span></a></li>


          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to "Import", import_path, class: "nav-link navbar-each-element" %></li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up",  new_user_registration_path, class: "nav-link navbar-each-element" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link navbar-each-element" %>
          </li>
        <% end %>
      </div>
    </ul>
  </nav>

app/views/layouts/partials/_top_header.html.erb
<div class="container-fluid bg-dark">
  <div class="row text-light pt-2 pb-2">
    <div class="col-3 pl-5">
      <% if user_signed_in? %>
        <%= link_to "Welcome #{current_user.first_name}", user_path(current_user.id), class: "text-light" %>
      <% else %>
        <%= link_to "Aviny", root_path, class: "text-light" %>
      <% end %>
    </div>
    <div class="col-5">



    </div>
    <div class="col-3 text-right">
      <nav class="nav justify-content-end">
        <% if user_signed_in? %>
          <a class="nav-link btn btn-sm btn-outline-light dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">Profile</a>
          <div class="dropdown-menu">
            <div class="btn-group-vertical full-width">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-light" %>
              <%= link_to "Account info", edit_user_registration_path, class: "btn btn-light" %>
            </div>
          <% else %>
            <a class="nav-link btn btn-sm btn-outline-light dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">contact</a>
          <div class="dropdown-menu">
            <div class="btn-group-vertical">
              <%= link_to "Contact", "#", class: "btn btn-light" %>
              <%= link_to "Support", "#", class: "btn btn-light" %>
            </div>
          <% end %>
        </div>
      </nav>
    </div>
  </div>
</div>